CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=30

CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3

CONFIG_SPI=y

CONFIG_ZMK_POINTING=y
CONFIG_PAW3395=y

CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6

CONFIG_ZMK_ESB_ENDPOINT=y
CONFIG_ZMK_ESB_ENDPOINT_CHANNEL_HOP=y
CONFIG_ZMK_ESB_ENDPOINT_CRITICAL_MAX_RETRANSMIT=y

CONFIG_ZMK_BATTERY_REPORTING=y

CONFIG_VFX_RGBLED_INDICATOR=y
CONFIG_VFX_LDO_PIN=y
CONFIG_VFX_CHRG_PIN=y

CONFIG_LARISKA_BLE_LED=y
